### ISSUE TITLE
This exception is occasionally thrown in clones “must be writeable (Parameter 'left')”

### ISSUE THREAD

**Issue by xlievo** [force-net/DeepCloner#13]
Expression must be writeable (Parameter 'left')
System.Linq.Expressions
   at System.Linq.Expressions.Expression.RequiresCanWrite(Expression expression, String paramName)
   at System.Linq.Expressions.Expression.Assign(Expression left, Expression right)
   at Force.DeepCloner.Helpers.DeepClonerExprGenerator.GenerateProcessMethod(Type type, Boolean unboxStruct)
   at Force.DeepCloner.Helpers.DeepClonerExprGenerator.GenerateClonerInternal(Type realType, Boolean asObject)
   at Force.DeepCloner.Helpers.DeepClonerGenerator.GenerateCloner(Type t, Boolean asObject)
   at Force.DeepCloner.Helpers.DeepClonerGenerator.<>c.<CloneClassRoot>b__1_0(Type t)
   at Force.DeepCloner.Helpers.DeepClonerCache.GetOrAddClass[T](Type type, Func`2 adder)
   at Force.DeepCloner.Helpers.DeepClonerGenerator.CloneClassRoot(Object obj)
   at Force.DeepCloner.Helpers.DeepClonerGenerator.CloneObject[T](T obj)
   at Force.DeepCloner.DeepClonerExtensions.DeepClone[T](T obj)

**Comment by force-net** [comment]
Can you provide some details? Do you have some dynamic code, lot of parallel executions and different classes, or something similar?
Which version of dotnet core do you use?

Currently, I found only one possible issue, but it can throw such exception in very rare cases.

**Comment by xlievo** [comment]
Almost all. Net versions have this problem because I've been using it for years
I need to copy subclasses of "system. Attribute" concurrently
If you can eliminate this problem, it will be perfect. Thank you again for your input

Sometimes throw exceptions very often, so I have to ask for help!
I'm not sure what information is useful for you

at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica`1.ExecuteAction(Boolean& yieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()
   at System.Linq.Expressions.Expression.RequiresCanWrite(Expression expression, String paramName)
   at System.Linq.Expressions.Expression.Assign(Expression left, Expression right)
   at Force.DeepCloner.Helpers.DeepClonerExprGenerator.GenerateProcessMethod(Type type, Boolean unboxStruct)
   at Force.DeepCloner.Helpers.DeepClonerExprGenerator.GenerateClonerInternal(Type realType, Boolean asObject)
   at Force.DeepCloner.Helpers.DeepClonerGenerator.GenerateCloner(Type t, Boolean asObject)
   at Force.DeepCloner.Helpers.DeepClonerGenerator.<>c.<CloneClassRoot>b__1_0(Type t)
   at Force.DeepCloner.Helpers.DeepClonerCache.GetOrAddClass[T](Type type, Func`2 adder)
   at Force.DeepCloner.Helpers.DeepClonerGenerator.CloneClassRoot(Object obj)
   at Force.DeepCloner.Helpers.DeepClonerGenerator.CloneObject[T](T obj)
   at Force.DeepCloner.DeepClonerExtensions.DeepClone[T](T obj)
   at Business.Attributes.AttributeBase.Clone[T]() in D:\Source\Repos\Business.Core\Business.Core\Auth\Attributes.cs:line 320
   at Business.Utils.Help.Clone[T](T attribute) in D:\Source\Repos\Business.Core\Business.Core\Utils\Help.cs:line 1324
   at Business.Bind.<>c.<GetArgGroup>b__37_5(ArgumentAttribute c) in D:\Source\Repos\Business.Core\Business.Core\Business\Bind.cs:line 1472
   at System.Linq.Enumerable.SelectListIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Business.Bind.GetArgGroup(List`1 argAttrAll, CurrentType current, String path, String owner, ConcurrentReadOnlyDictionary`2 commands, Type resultType, Type resultTypeDefinition, Boolean hasUse, Boolean& hasLower, Boolean& hasCollectionAttr, String root, List`1 log, List`1 inLog) in D:\Source\Repos\Business.Core\Business.Core\Business\Bind.cs:line 1470
   at Business.Bind.GetArgChild(Type type, String path, ConcurrentReadOnlyDictionary`2 commands, List`1& definitions, Type resultType, Type resultTypeDefinition, IList`1 useTypes, Boolean& hasLower, String root, ReadOnlyCollection`1 childrens) in D:\Source\Repos\Business.Core\Business.Core\Business\Bind.cs:line 1392
   at Business.Bind.<>c__DisplayClass29_0.<GetInterceptorMetaData>b__0(KeyValuePair`2 methodMeta) in D:\Source\Repos\Business.Core\Business.Core\Business\Bind.cs:line 1161
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)

**Comment by force-net** [comment]
I'll try to reproduce this issue. You can try to clone required type somewhere on application start without parallel processing. It will produce cloner class and other cloning operations should perform successfully. Currently, mass parallel init may cause such problem.

**Comment by xlievo** [comment]
Since parallel processing may be necessary for me, changing the process may lead to more extensive rewriting
so,
Thank you. Hope to solve this problem
